'use strict';

const { Router } = require('express');

const healthRoutes = require('../modules/health/health.routes');
const authRoutes = require('../modules/auth/auth.routes');
const deviceRoutes = require('../modules/devices/devices.routes');
const bulletinAdminRoutes = require('../modules/bulletins/bulletins.admin.routes');
const bulletinEmployeeRoutes = require('../modules/bulletins/bulletins.employee.routes');
const vehicleCheckAdminRoutes = require('../modules/vehicle-checks/vehicle-checks.admin.routes');
const vehicleCheckEmployeeRoutes = require('../modules/vehicle-checks/vehicle-checks.employee.routes');
const timesheetAdminRoutes = require('../modules/timesheets/timesheets.admin.routes');
const timesheetEmployeeRoutes = require('../modules/timesheets/timesheets.employee.routes');
const incidentAdminRoutes = require('../modules/incidents/incidents.admin.routes');
const incidentEmployeeRoutes = require('../modules/incidents/incidents.employee.routes');
const contactEmployeeRoutes = require('../modules/contacts/contacts.employee.routes');
const documentAdminRoutes = require('../modules/documents/documents.admin.routes');
const documentEmployeeRoutes = require('../modules/documents/documents.employee.routes');
const hrAdminRoutes = require('../modules/hr/hr.admin.routes');
const usersAdminRoutes = require('../modules/users/users.admin.routes');
const erAdminRoutes = require('../modules/equipment-register/er.admin.routes');
const vrAdminRoutes = require('../modules/vehicle-register/vr.admin.routes');
const prAdminRoutes = require('../modules/plant-register/pr.admin.routes');
const ecAdminRoutes = require('../modules/equipment-checks/ec.admin.routes');
const ecEmployeeRoutes = require('../modules/equipment-checks/ec.employee.routes');
const onboardingEmployeeRoutes = require('../modules/onboarding/onboarding.employee.routes');
const siAdminRoutes = require('../modules/site-inspections/si.admin.routes');
const siEmployeeRoutes = require('../modules/site-inspections/si.employee.routes');
const viAdminRoutes = require('../modules/vehicle-inspections/vi.admin.routes');
const viEmployeeRoutes = require('../modules/vehicle-inspections/vi.employee.routes');
const wjAdminRoutes = require('../modules/wildanet-jobs/wj.admin.routes');
const wjEmployeeRoutes = require('../modules/wildanet-jobs/wj.employee.routes');
const wrAdminRoutes = require('../modules/work-records/wr.admin.routes');
const wrEmployeeRoutes = require('../modules/work-records/wr.employee.routes');
const ctAdminRoutes = require('../modules/clegg-testing/ct.admin.routes');
const ctEmployeeRoutes = require('../modules/clegg-testing/ct.employee.routes');
const wraAdminRoutes = require('../modules/wildanet-risk-assessments/wra.admin.routes');
const wraEmployeeRoutes = require('../modules/wildanet-risk-assessments/wra.employee.routes');
const pfrAdminRoutes = require('../modules/pia-fibre-risk/pfr.admin.routes');
const pfrEmployeeRoutes = require('../modules/pia-fibre-risk/pfr.employee.routes');
const civAdminRoutes = require('../modules/civils/civ.admin.routes');
const civEmployeeRoutes = require('../modules/civils/civ.employee.routes');
const tflAdminRoutes = require('../modules/tfl/tfl.admin.routes');
const tflEmployeeRoutes = require('../modules/tfl/tfl.employee.routes');

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/devices', deviceRoutes);

// Business modules — /admin/* and /employee/* top-level split
router.use('/admin/bulletins', bulletinAdminRoutes);
router.use('/employee/bulletins', bulletinEmployeeRoutes);
router.use('/admin/vehicle-checks', vehicleCheckAdminRoutes);
router.use('/employee/vehicle-checks', vehicleCheckEmployeeRoutes);
router.use('/admin/timesheets', timesheetAdminRoutes);
router.use('/employee/timesheets', timesheetEmployeeRoutes);
router.use('/admin/incidents', incidentAdminRoutes);
router.use('/employee/incidents', incidentEmployeeRoutes);
router.use('/employee/contacts', contactEmployeeRoutes);
router.use('/admin/documents', documentAdminRoutes);
router.use('/employee/documents', documentEmployeeRoutes);
router.use('/admin/hr', hrAdminRoutes);
router.use('/admin/users', usersAdminRoutes);
router.use('/admin/equipment-register', erAdminRoutes);
router.use('/admin/vehicle-register', vrAdminRoutes);
router.use('/admin/plant-register', prAdminRoutes);
router.use('/admin/equipment-checks', ecAdminRoutes);
router.use('/employee/equipment-checks', ecEmployeeRoutes);
router.use('/employee/onboarding', onboardingEmployeeRoutes);
router.use('/admin/site-inspections', siAdminRoutes);
router.use('/employee/site-inspections', siEmployeeRoutes);
router.use('/admin/vehicle-inspections', viAdminRoutes);
router.use('/employee/vehicle-inspections', viEmployeeRoutes);
router.use('/admin/wildanet-jobs', wjAdminRoutes);
router.use('/employee/wildanet-jobs', wjEmployeeRoutes);
router.use('/admin/work-records', wrAdminRoutes);
router.use('/employee/work-records', wrEmployeeRoutes);
router.use('/admin/clegg-testing', ctAdminRoutes);
router.use('/employee/clegg-testing', ctEmployeeRoutes);
router.use('/admin/wildanet-risk-assessments', wraAdminRoutes);
router.use('/employee/wildanet-risk-assessments', wraEmployeeRoutes);
router.use('/admin/pia-fibre-risk', pfrAdminRoutes);
router.use('/employee/pia-fibre-risk', pfrEmployeeRoutes);
router.use('/admin/civils', civAdminRoutes);
router.use('/employee/civils', civEmployeeRoutes);
router.use('/admin/tfl', tflAdminRoutes);
router.use('/employee/tfl', tflEmployeeRoutes);

module.exports = router;
