'use strict';

/**
 * Domain-prefixed error codes. Clients switch on `error.code` — never on `error.message`.
 * Add new codes here rather than inventing them at call sites.
 */

const ERROR_CODES = Object.freeze({
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_LEVEL_UNKNOWN: 'AUTH_LEVEL_UNKNOWN',
  AUTH_USER_DISABLED: 'AUTH_USER_DISABLED',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',

  // Uploads
  UPLOAD_INVALID_MIME: 'UPLOAD_INVALID_MIME',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',

  // DB
  DB_UNAVAILABLE: 'DB_UNAVAILABLE',
});

module.exports = ERROR_CODES;
