'use strict';

const swaggerJsdoc = require('swagger-jsdoc');
const env = require('./env');

const definition = {
  openapi: '3.0.3',
  info: {
    title: 'LTraffic Unified API',
    version: '0.1.0',
    description:
      'REST API serving LTraffic Admin and Employee mobile apps. Legacy PHP web keeps its own session auth.',
    contact: { name: 'LTraffic Engineering' },
  },
  servers: [{ url: `${env.PUBLIC_BASE_URL}${env.API_PREFIX}`, description: env.NODE_ENV }],
  tags: [
    // ── Shared ─────────────────────────────────────────────────
    { name: 'System', description: 'Health checks and system status' },
    {
      name: 'Authentication',
      description: [
        'JWT-based authentication for the LTraffic mobile apps (Admin and Employee).',
        '',
        '## Token Architecture',
        '',
        '| Token | Type | Lifetime | Storage |',
        '|-------|------|----------|---------|',
        '| Access Token | JWT (HS256) | 15 minutes | Memory / secure variable |',
        '| Refresh Token | 64-char opaque hex | 60 days | Keychain / EncryptedSharedPreferences |',
        '',
        '## Authentication Flow',
        '',
        '1. **Login** — `POST /auth/login` with credentials → receive `accessToken` + `refreshToken` + user profile.',
        '2. **Use API** — send `Authorization: Bearer <accessToken>` on every request.',
        '3. **Token expires** — API returns `401 AUTH_TOKEN_EXPIRED`.',
        '4. **Refresh** — `POST /auth/refresh` with the old `refreshToken` → receive a new pair. The old refresh token is revoked (rotation).',
        '5. **Retry** — repeat the failed request with the new `accessToken`.',
        '6. **Logout** — `POST /auth/logout` with the current `refreshToken` to revoke it. Discard both tokens.',
        '',
        '## User Type Routing',
        '',
        'The `userType` field in the login response tells the mobile app which UI to show:',
        '- `admin` — levels 1 (Admin), 4 (Admin1), 7 (Admin2), 8 (Essex Supervisor)',
        '- `employee` — all other levels',
        '',
        '## Common Error Codes',
        '',
        '| Code | HTTP | Meaning |',
        '|------|------|---------|',
        '| `AUTH_INVALID_CREDENTIALS` | 401 | Wrong username/email or password |',
        '| `AUTH_USER_DISABLED` | 403 | User\'s role/level is disabled |',
        '| `AUTH_TOKEN_EXPIRED` | 401 | Access token has expired — call `/auth/refresh` |',
        '| `AUTH_TOKEN_INVALID` | 401 | Malformed or tampered JWT |',
        '| `AUTH_REFRESH_INVALID` | 401 | Refresh token unknown, expired, or already used — user must log in again |',
        '| `UNAUTHORIZED` | 401 | No Authorization header provided |',
        '| `RATE_LIMITED` | 429 | Too many requests — back off and retry |',
        '',
        '## PHP Compatibility',
        '',
        'Passwords are read/written as MD5 in `login_users.password` (same column PHP uses).',
        'On login the Node API lazy-caches a bcrypt hash in `lt_user_credentials` for',
        'future comparison performance. Both systems always work with the same password.',
      ].join('\n'),
    },
    {
      name: 'Devices',
      description: [
        'FCM push notification device token management for both Admin and Employee mobile apps.',
        '',
        '## How It Works',
        '',
        '1. **Register** — `POST /devices/register` with the FCM token after login or app launch. Upsert-safe — re-registering a token that belongs to another user (shared device) transfers ownership automatically.',
        '2. **Unregister** — `POST /devices/unregister` to revoke the token on logout or notification opt-out. Only the token owner can revoke.',
        '3. **List** — `GET /devices` returns the current user\'s active (non-revoked) tokens.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `lt_device_tokens` | FCM tokens with user, platform, appVersion, revoked_at |',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| All authenticated users | Full access |',
        '',
        '## PHP Compatibility',
        '',
        'This is a new Node-only table (`lt_device_tokens`). PHP does not manage push tokens.',
      ].join('\n'),
    },

    // ── Employee App ───────────────────────────────────────────
    {
      name: 'Bulletins',
      description: [
        'Employee-facing bulletin reading and acknowledgement.',
        '',
        'The mobile app should call `GET /employee/bulletins/pending` on every launch and **block navigation** if the result is non-empty — employees must read and acknowledge all active bulletins before using other app features.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `bulletinnew` | Bulletin content and active/inactive flag |',
        '| `bulletinread` | Per-user read tracking (one row per user per bulletin) |',
        '| `bulletinconfirm` | Audit log of every acknowledgement click |',
        '',
        '## Key Business Rules',
        '',
        '- **Pending endpoint** returns unread active bulletins (not paginated — returns all at once)',
        '- **Acknowledge** is idempotent for read tracking (`bulletinread`) but NOT for audit logging (`bulletinconfirm` — every call inserts a row)',
        '- `is_read` flag is derived from `bulletinread` for the current user',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| All authenticated users | Full access |',
        '',
        '## PHP Compatibility',
        '',
        'Reads from / writes to the same `bulletinnew`, `bulletinread`, and `bulletinconfirm` tables as PHP. Replaces the forced-read popup and bulletin list in the PHP employee area.',
      ].join('\n'),
    },
    {
      name: 'Contacts',
      description: [
        'Read-only company contact directory. Employees can browse and search colleagues by name to find phone numbers, email addresses, and job titles.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `hr` | Employee records (shared with HR module) |',
        '',
        '## Fields Returned',
        '',
        '`employeeid`, `firstname`, `surname`, `ltrafficphone`, `ltrafficemail`, `jobtitle`, `linemanager`, `location`, `photoimage`',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| All authenticated users | Read-only (list + detail) |',
        '',
        '## PHP Compatibility',
        '',
        'Reads from the same `hr` table as PHP. Replaces the employee contact directory.',
      ].join('\n'),
    },
    {
      name: 'Documents',
      description: [
        'Read-only access to company documents across four categories: Policies, Method Statements, Processes, and CoSHH (Control of Substances Hazardous to Health).',
        '',
        'Each category maps to a separate database table but shares the same API pattern. The `:type` path parameter selects the category.',
        '',
        '## Document Types',
        '',
        '| Type Slug | Table | Columns |',
        '|-----------|-------|---------|',
        '| `policies` | `policies` | pol1 (ref), pol2 (title), pol3 (version) |',
        '| `method-statements` | `methodstatements` | ms1, ms2, ms3 |',
        '| `processes` | `processes` | pro1, pro2, pro3 |',
        '| `coshh` | `coshh` | cos1, cos2, cos3 |',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| All authenticated users | Read-only (list + detail) |',
        '',
        '## PHP Compatibility',
        '',
        'Reads from the same four document tables as PHP. Replaces the employee document library views.',
      ].join('\n'),
    },
    {
      name: 'Vehicle Checks',
      description: [
        'Daily vehicle safety check submission and history. Employees complete a structured checklist covering planning, circle check, under the hood, behind the wheel, and trailer & load — then rate overall condition and safety.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `vehicle` | Vehicle check submissions |',
        '| `upload_vehicle` | Attached evidence photos/PDFs |',
        '',
        '## Status Values',
        '',
        '| Field | Values |',
        '|-------|--------|',
        '| `vehiclecondition` | Good, Average, Poor, Very Poor, Dangerous, Closed |',
        '| `safe` | Safe, Unsafe, Closed |',
        '',
        '## Key Business Rules',
        '',
        '- **Throttled:** employees can only submit one check per 8 hours per driver',
        '- `drivername` is auto-set from the JWT — employees cannot submit on behalf of others',
        '- Supports image upload on submission',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| All authenticated users | Submit + view own history |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to the same `vehicle` table as PHP. Replaces the employee vehicle check form.',
      ].join('\n'),
    },
    {
      name: 'Timesheets',
      description: [
        'Weekly timesheet submission and history. Employees can save drafts and submit finalised timesheets for admin approval.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `timesheet` | Timesheet records with 7-day breakdown |',
        '',
        '## Status Workflow',
        '',
        '```',
        'Draft → Submitted → Approved / Rejected',
        '```',
        '',
        '- **Draft** — saved but not yet submitted; employee can edit',
        '- **Submitted** — locked for employee; awaiting admin review',
        '- **Approved / Rejected** — admin decision (rejected timesheets can be resubmitted)',
        '',
        '## Data Model',
        '',
        'Each timesheet contains 7 days of data flattened to columns: `date1`–`date7`, `hours1`–`hours7`, `location1`–`location7`, `activity1`–`activity7`, `contract1`–`contract7`.',
        '',
        '## Key Business Rules',
        '',
        '- `ltrafficid` and `name` auto-set from JWT',
        '- Employees can submit (status = Submitted) or save as draft (status = Draft)',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| All authenticated users | Submit, draft, view own |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to the same `timesheet` table as PHP. Replaces the employee timesheet submission form.',
      ].join('\n'),
    },
    {
      name: 'Incidents',
      description: [
        'Health & Safety incident reporting. Employees can report incidents with photos and view their submission history.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `healthsafety` | Incident records |',
        '| `upload_hs` | Attached evidence photos/PDFs |',
        '',
        '## Incident Types',
        '',
        '`Accident`, `Customer Complaint`, `Customer Engagement`, `Environmental`, `Incident`, `Near Miss`, `Service Strike`',
        '',
        '## Status Workflow',
        '',
        '```',
        'Open → In Progress → Closed',
        '```',
        '',
        '## Key Business Rules',
        '',
        '- Employees can attach up to 10 images on submission',
        '- `operativesname` and `reportedby` auto-set from JWT',
        '- Rich data model: injury tracking, witness info, RIDDOR fields',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| All authenticated users | Submit + view own |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to the same `healthsafety` and `upload_hs` tables as PHP. Replaces the employee incident report form.',
      ].join('\n'),
    },
    {
      name: 'Equipment Checks',
      description: [
        'PUWER-compliant equipment and plant inspection submission. Employees complete a 13-point safety checklist and rate overall condition.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `equipmentcheck` | Check submissions |',
        '| `upload_presite` | Admin-attached documents |',
        '',
        '## 13-Point Checklist',
        '',
        'Brakes, Steering, Seatbelt, Mirrors, Tyres, Wheel Security, Rotating Beacon, Horn, Warning Lights, Coolant, Seat, Access, Fuel — each Pass/Fail.',
        '',
        '## Status Values',
        '',
        '| Field | Values |',
        '|-------|--------|',
        '| `cond` | Good, Average, Poor, Very Poor, Dangerous |',
        '| `safe` | Safe, Unsafe |',
        '',
        '## Key Business Rules',
        '',
        '- At least 1 image required on submission (max 4)',
        '- Comma-separated image paths stored in `image` column',
        '- `operativesname` auto-set from JWT',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Civils Trailer Driver (6), Essex Supervisor (8) | Submit + view own |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to the same `equipmentcheck` table as PHP. Replaces the employee equipment check form.',
      ].join('\n'),
    },
    {
      name: 'Onboarding',
      description: [
        'Self-service employee onboarding form. New employees submit their personal details, emergency contacts, and employment information on first login.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `hr` | Employee record (created on submit) |',
        '| `login_users` | Onboarding flag (`onboarding` column) |',
        '',
        '## How It Works',
        '',
        '1. `GET /employee/onboarding/status` — check if onboarding is complete (`login_users.onboarding`)',
        '2. `POST /employee/onboarding` — submit the form (creates `hr` row, sets `onboarding = \'1\'`)',
        '3. `GET /employee/onboarding` — retrieve submitted data',
        '',
        '## Key Business Rules',
        '',
        '- Photo and signature paths auto-generated from `name1` field (PHP convention: `employeephoto/{name1}.jpg`)',
        '- Once submitted (`onboarding = \'1\'`), the form cannot be re-submitted',
        '- Collects: personal details, 2 emergency contacts, NI number, start date',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| All authenticated users | Full access |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to the same `hr` table and `login_users.onboarding` flag as PHP.',
      ].join('\n'),
    },
    {
      name: 'Site Inspections',
      description: [
        'Multi-part PUWER site safety inspection wizard (8 parts). Employees create inspections linked to a parent civils or Wildanet job and complete sections over time.',
        '',
        '## Source Discriminator',
        '',
        'A `source` query parameter selects the inspection type:',
        '',
        '| Source | Inspection Table | Parent Table |',
        '|--------|-----------------|--------------|',
        '| `civils` | `insp` | `civils` |',
        '| `wildanet` | `winsp` | `wildanet` |',
        '',
        'Both tables share an identical 94-column schema.',
        '',
        '## 8-Part Wizard',
        '',
        '| Part | Section | Key Fields |',
        '|------|---------|------------|',
        '| 1 | Site Details (INSERT) | Auto-populated from parent job + operatives + activities |',
        '| 2 | Welfare & First Aid | 15 inspection items |',
        '| 3 | Site Set Up | 6 items |',
        '| 4 | Housekeeping | 7 items |',
        '| 5 | Health & Environment | 6 items |',
        '| 6 | PUWER Compliance | 14 items |',
        '| 7 | Traffic Management | 5 items |',
        '| 8 | Summary & Sign-off | Sets status to "Inspection Awaiting Review" |',
        '',
        '## Status Workflow',
        '',
        '```',
        'In Progress → (Part 8) → Inspection Awaiting Review',
        '```',
        '',
        'Admin then sets final status: Pass / Completed / Failed / Follow up Required.',
        '',
        '## Key Business Rules',
        '',
        '- Part 1 auto-populates from parent job: site ref, location, client, ganger',
        '- Each part supports up to 4 image uploads',
        '- Employee list filters by `in3` (completed by = current user)',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Civils Trailer Driver (6), Essex Supervisor (8) | Create + continue + view own |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to `insp` / `winsp` tables matching PHP. Replaces the 8-screen inspection wizard.',
      ].join('\n'),
    },
    {
      name: 'Vehicle Inspections',
      description: [
        'Multi-part Vehicle Inspection Checklist (VIC) wizard (4 parts) with linked Inspection Repair (VIR) records. Covers interior, exterior, mechanical, and final assessment.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `vic` | Vehicle inspection records (109 columns) |',
        '| `vir` | Linked inspection repair records |',
        '| `vr` | Vehicle register (lookup for registration) |',
        '',
        '## 4-Part Wizard',
        '',
        '| Part | Section | Key Fields |',
        '|------|---------|------------|',
        '| 1 | Interior + Exterior + Glass (INSERT) | vic1–vic36, linked to VR entry |',
        '| 2 | Suspension + Steering + Engine + Tyres | vic37–vic77 |',
        '| 3 | Lights + Exhaust | vic87–vic100 (note: vic78–vic86 do not exist) |',
        '| 4 | Final Assessment + Signature | vic101–vic109, sets status to "Completed" |',
        '',
        '## Status Workflow',
        '',
        '```',
        'In Progress → (Part 4) → Completed',
        '```',
        '',
        '## Inspection Repairs (VIR)',
        '',
        'After completing an inspection, employees can log repair records against it. VIR records are always created with status "Completed" and include defect details, works description, and pass/fail result.',
        '',
        '## Key Business Rules',
        '',
        '- Part 1 auto-populates name (JWT) and vehicle reg (from VR lookup)',
        '- Part 4 auto-generates employee signature path',
        '- Each part supports up to 4 image uploads',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Civils Trailer Driver (6), Essex Supervisor (8), Admin2 (7) | Create Part 1 |',
        '| Admin (1), Admin1 (4), Civils Trailer Driver (6), Essex Supervisor (8) | Continue + view + add repairs |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to `vic` and `vir` tables matching PHP. Replaces the 4-screen VIC wizard and repair form.',
      ].join('\n'),
    },
    {
      name: 'Wildanet Jobs',
      description: [
        'Read-only view of Wildanet civils job records. Employees can browse active jobs and download associated documents.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `wildanet` | Job records |',
        '| `wupload_data` | Job documents and attachments |',
        '',
        '## Key Business Rules',
        '',
        '- Employee view excludes completed/inactive jobs (Completed, Cancelled, Closed, Invoiced, Awaiting Invoicing)',
        '- Documents are read-only for employees; uploads are admin-only',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Admin2 (7), Civils Trailer Driver (6), Essex Supervisor (8) | List + view jobs |',
        '| + Customer (9) | View documents only |',
        '',
        '## PHP Compatibility',
        '',
        'Reads from the same `wildanet` and `wupload_data` tables as PHP.',
      ].join('\n'),
    },
    {
      name: 'Civils',
      description: [
        'Civils job register — read-only employee view. Employees can browse active civils jobs and view attached documents.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `civils` | Job register records |',
        '| `upload_data` | Job documents and attachments |',
        '',
        '## Key Business Rules',
        '',
        '- Employee view excludes completed/inactive jobs (Completed, Cancelled, Closed, Invoiced, Awaiting Invoicing)',
        '- Documents are read-only for employees; uploads are admin-only',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Admin2 (7), Civils Trailer Driver (6), Essex Supervisor (8), Customer (9) | List + view + documents |',
        '',
        '## PHP Compatibility',
        '',
        'Reads from the same `civils` and `upload_data` tables as PHP.',
      ].join('\n'),
    },
    {
      name: 'TFL',
      description: [
        'TFL (Transport for London) job register and materials — read-only employee view. Employees can browse active TFL jobs, view attached documents, and check material inventory.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `tfl` | TFL job register records |',
        '| `upload_tfl` | Job documents and attachments |',
        '| `tflmaterial` | Material inventory |',
        '',
        '## Key Business Rules',
        '',
        '- Employee view excludes 7 inactive statuses (Pending, Delayed, Completed, Cancelled, Awaiting Invoicing, Invoiced, Closed)',
        '- Documents and materials are read-only for employees; management is admin-only',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Civils TFL Driver (5) | List + view + documents + materials |',
        '',
        '## PHP Compatibility',
        '',
        'Reads from the same `tfl`, `upload_tfl`, and `tflmaterial` tables as PHP.',
      ].join('\n'),
    },
    {
      name: 'Work Records',
      description: [
        'Field work recording for infrastructure (fibre/telecom) projects. Employees submit records of work performed with location details and supporting images.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `workrecord` | Work records |',
        '',
        '## Key Business Rules',
        '',
        '- Status auto-set to "Pending" on creation',
        '- Supports up to 10 image uploads per record',
        '- `lt1` (Recorded By) and `lt2` (Date/Time) auto-set from JWT and server time',
        '- Data fields: Road Name, Cabinet Area, Primary Node, Secondary Node, Structure ID, Type of Works, Work Status, Notes, Ducting Length',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Admin2 (7), Civils Trailer Driver (6), Essex Supervisor (8) | Submit + view own |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to the same `workrecord` table as PHP.',
      ].join('\n'),
    },
    {
      name: 'Clegg Testing',
      description: [
        'Clegg hammer soil compaction test recording. Employees submit test results for reinstatement quality assurance.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `cleggtesting` | Test records |',
        '',
        '## Key Business Rules',
        '',
        '- `ct3` (Date) and `ct4` (Conducted By) auto-set from server time and JWT',
        '- Supports up to 6 image uploads per record',
        '- Data fields: Job Number, Location, Cabinet Area, Surface Type, Test Unit, Calibration Expiry, Test Reading, Result (Pass/Fail), Re-Test Reading, Re-Test Result, Notes',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Civils Trailer Driver (6), Essex Supervisor (8) | Create |',
        '| + Admin2 (7) | View (list + detail) |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to the same `cleggtesting` table as PHP.',
      ].join('\n'),
    },
    {
      name: 'Wildanet Risk Assessments',
      description: [
        'Multi-part Wildanet risk assessment wizard (5 parts). Employees create risk assessments linked to Wildanet parent jobs covering site details, personnel, hazards, permit to dig, and end-of-day sign-off.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `wra` | Risk assessment records (74 columns) |',
        '| `wildanet` | Parent job (lookup for auto-population) |',
        '',
        '## 5-Part Wizard',
        '',
        '| Part | Section | Key Fields |',
        '|------|---------|------------|',
        '| 1 | Site Details (INSERT) | Auto-populated from parent Wildanet job |',
        '| 2 | Personnel In Attendance | Personnel names and roles |',
        '| 3 | Hazards | Identified hazards and controls |',
        '| 4 | Permit to Dig | Includes employee signature |',
        '| 5 | End of Day Sign-off | Sets status to "RA Completed", includes signature |',
        '',
        '## Status Workflow',
        '',
        '```',
        'In Progress → (Part 5) → RA Completed',
        '```',
        '',
        '## Key Business Rules',
        '',
        '- Part 1 auto-populates site ref, location, client, dates from parent Wildanet job',
        '- Parts 4 and 5 auto-generate signature paths from user name',
        '- Each part supports up to 4 image uploads',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Civils Trailer Driver (6), Essex Supervisor (8) | Create + continue + view own |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to the same `wra` table as PHP. Replaces the 5-screen risk assessment wizard.',
      ].join('\n'),
    },
    {
      name: 'PIA & Fibre Risk',
      description: [
        'Pre-work risk assessment permits for PIA (Physical Infrastructure Access) fibre installation. Three separate permit subtypes cover different work scenarios.',
        '',
        '## Permit Types',
        '',
        '| Type | Table | Purpose |',
        '|------|-------|---------|',
        '| WAH (Working at Height) | `wah` | Ladder/pole work — 14 safety fields |',
        '| UG (Underground Works) | `ug` | Below-ground work — 13 safety fields |',
        '| MEWP (Mobile Elevated Work Platform) | `mewp` | Cherry picker/platform work — 15 safety fields |',
        '',
        '## Key Business Rules',
        '',
        '- All permits created with status "Submitted" (no multi-part workflow)',
        '- Operative name and datetime auto-set from JWT and server time',
        '- Shared node fields across all types: Primary Node, SN Type, Secondary Node',
        '- Supports up to 10 image uploads per permit',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Civils Trailer Driver (6), Essex Supervisor (8) | Create |',
        '| + Admin2 (7) | View (list + detail) |',
        '',
        '## PHP Compatibility',
        '',
        'Writes to `wah`, `ug`, and `mewp` tables matching PHP. Replaces the PHP permit forms.',
      ].join('\n'),
    },

    // ── Admin App ──────────────────────────────────────────────
    {
      name: 'Admin - Bulletins',
      description: [
        'Bulletin management for administrators. Create, edit, and delete bulletins, and view which employees have acknowledged each one.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `bulletinnew` | Bulletin content and active/inactive flag |',
        '| `bulletinread` | Per-user read tracking |',
        '| `bulletinconfirm` | Audit trail of acknowledgements |',
        '',
        '## Key Features',
        '',
        '- Create/update bulletins with image and download attachments',
        '- View read confirmation list per bulletin (`bulletinread` joined with user names)',
        '- Toggle active/inactive status',
        '- Search by title or reference code',
        '- Filter by status (active/inactive)',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4) | Full CRUD + view readers |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `bulletinnew` table as PHP admin. Upload paths: `bulletin/` for images and downloads.',
      ].join('\n'),
    },
    {
      name: 'Admin - Documents',
      description: [
        'Document control management across four categories: Policies, Method Statements, Processes, and CoSHH.',
        '',
        '## Document Types',
        '',
        '| Type Slug | Table | Columns |',
        '|-----------|-------|---------|',
        '| `policies` | `policies` | pol1 (ref), pol2 (title), pol3 (version) |',
        '| `method-statements` | `methodstatements` | ms1, ms2, ms3 |',
        '| `processes` | `processes` | pro1, pro2, pro3 |',
        '| `coshh` | `coshh` | cos1, cos2, cos3 |',
        '',
        '## Key Features',
        '',
        '- Full CRUD for all four document types via the `:type` path parameter',
        '- Upload document files per record',
        '- Documents are immediately visible to all employees',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4) | View |',
        '| Admin (1) | Create + edit + delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same four document tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Vehicle Checks',
      description: [
        'Vehicle check management and review. Administrators can view all employee submissions, add evidence documents, and close out checks.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `vehicle` | Vehicle check submissions |',
        '| `upload_vehicle` | Attached evidence photos/PDFs |',
        '',
        '## Status Values',
        '',
        '| Field | Values |',
        '|-------|--------|',
        '| `vehiclecondition` | Good, Average, Poor, Very Poor, Dangerous, Closed |',
        '| `safe` | Safe, Unsafe, Closed |',
        '',
        '## Key Features',
        '',
        '- Filter views: `action-required` (Unsafe or poor condition), `closed`',
        '- Attach evidence documents to existing checks',
        '- Search by driver name or vehicle registration',
        '- Admin can create checks on behalf of employees',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Admin2 (7) | View |',
        '| Admin (1), Admin1 (4) | Create + edit |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `vehicle` and `upload_vehicle` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Timesheets',
      description: [
        'Timesheet management, approval, and rejection. Administrators review employee submissions and approve or reject them.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `timesheet` | Timesheet records with 7-day breakdown |',
        '',
        '## Status Workflow',
        '',
        '```',
        'Draft → Submitted → Approved / Rejected',
        '```',
        '',
        '## Key Features',
        '',
        '- Filter by status: `submitted` (includes Rejected), `approved`, `draft`, `all`',
        '- Approve or reject individual timesheets with one click',
        '- Create timesheets on behalf of employees',
        '- Search by employee name or LTraffic ID',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4) | View + approve/reject + create |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `timesheet` table as PHP admin. Approval/rejection writes to the same status column.',
      ].join('\n'),
    },
    {
      name: 'Admin - Incidents',
      description: [
        'Health & Safety incident management. Administrators review incident reports, update investigation status, and attach evidence.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `healthsafety` | Incident records |',
        '| `upload_hs` | Attached evidence photos/PDFs |',
        '',
        '## Incident Types',
        '',
        '`Accident`, `Customer Complaint`, `Customer Engagement`, `Environmental`, `Incident`, `Near Miss`, `Service Strike`',
        '',
        '## Status Workflow',
        '',
        '```',
        'Open → In Progress → Closed',
        '```',
        '',
        '## Key Features',
        '',
        '- Dedicated status-change endpoint with investigation notes',
        '- Attach evidence documents to incidents',
        '- Create incidents on behalf of employees',
        '- RIDDOR reporting fields for regulatory compliance',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Essex Supervisor (8) | View |',
        '| Admin (1), Admin1 (4) | Edit + status change + create |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `healthsafety` and `upload_hs` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - HR',
      description: [
        'Employee HR record management. Full lifecycle management of employee personal, employment, and emergency contact records with document storage.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `hr` | Employee records |',
        '| `upload_hr` | HR documents (licences, contracts, checks) |',
        '',
        '## Document Types',
        '',
        '`Driver Eyesight Check`, `Driving Licence`, `Driving Licence Check`, `Ladder Inspection`, `Medical Check`, `Passport`, `PPE Issue`, `Service Contract`, `Toolbox Talk`, `Other`',
        '',
        '## Key Features',
        '',
        '- Full employee record: personal details, DOB, address, NI number',
        '- Two emergency contacts per employee',
        '- Employment info: employee ID, job title, location, line manager, salary, dates',
        '- Typed document management with upload and listing',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4) | View + edit |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `hr` and `upload_hr` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Users',
      description: [
        'User account management. Create, edit, and delete login accounts with role assignment and password management.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `login_users` | User accounts and credentials |',
        '| `lt_user_credentials` | Bcrypt password sidecar (Node-only) |',
        '| `lt_refresh_tokens` | Active refresh tokens |',
        '',
        '## Key Features',
        '',
        '- Username/email uniqueness enforcement',
        '- Dual-write password handling: MD5 (PHP compatibility) + bcrypt sidecar',
        '- Password update triggers all refresh token revocation',
        '- User deletion cascades: tokens → credentials → user record',
        '- Role assignment via `user_level` field',
        '',
        '## Teams',
        '',
        '`Director`, `Traffic Signals Installation`, `Traffic Signals Civils`, `Traffic Signal Maintenance`, `Utilities Civils`, `Office Staff`, `Customer`',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4) | View |',
        '| Admin (1) | Create + edit + delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `login_users` table as PHP. Passwords are written as MD5 to maintain PHP login compatibility.',
      ].join('\n'),
    },
    {
      name: 'Admin - Equipment Register',
      description: [
        'Equipment asset register management. Track company equipment with serial numbers, allocation, condition, and expiry dates.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `er` | Equipment register records |',
        '| `upload_er` | Equipment documents (condition photos, calibration certs) |',
        '',
        '## Document Types',
        '',
        '`Condition Image`, `Service / Calibration Expiry`, `Other`',
        '',
        '## Key Features',
        '',
        '- Full CRUD for equipment assets: item, description, ident (serial number), allocated to, condition, expiry',
        '- Typed document management per item',
        '- Sorted by ident (serial number) ascending',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4) | View + create + edit |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `er` and `upload_er` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Vehicle Register',
      description: [
        'Vehicle fleet register management with active/archived views. Track registration, allocation, and expiry dates (MOT, tax, service).',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `vr` | Vehicle register records |',
        '| `upload_vr` | Vehicle documents |',
        '',
        '## Active vs Archived',
        '',
        '| `cond` Value | Meaning |',
        '|-------------|---------|',
        '| `Yes` | Active vehicle |',
        '| `No` | Archived vehicle |',
        '',
        'Separate list endpoints for active (`GET /`) and archived (`GET /archived`) vehicles.',
        '',
        '## Key Features',
        '',
        '- Track MOT expiry (`mexpiry`), tax expiry (`texpiry`), service expiry (`sexpiry`)',
        '- Document management per vehicle',
        '- Sorted by registration ascending',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Essex Supervisor (8), Admin2 (7) | List |',
        '| Admin (1), Admin1 (4), Admin2 (7) | View detail + create |',
        '| Admin (1), Admin1 (4) | Edit |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `vr` and `upload_vr` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Plant Register',
      description: [
        'Plant asset register management. Track company plant items with serial numbers, allocation, condition, and service/calibration expiry.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `pr` | Plant register records |',
        '| `upload_pr` | Plant documents |',
        '',
        '## Document Types',
        '',
        '`Condition Image`, `Service / Calibration Expiry`, `Other`',
        '',
        '## Key Features',
        '',
        '- Identical structure to Equipment Register but for plant items',
        '- Sorted by expiry date ascending (soonest-expiring first)',
        '- Typed document management per item',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4) | View + create + edit |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `pr` and `upload_pr` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Equipment Checks',
      description: [
        'Equipment check management and review. Administrators can view all employee equipment inspection submissions, attach documents, and update records.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `equipmentcheck` | Check submissions |',
        '| `upload_presite` | Admin-attached documents |',
        '',
        '## Status Values',
        '',
        '| Field | Values |',
        '|-------|--------|',
        '| `cond` | Good, Average, Poor, Very Poor, Dangerous |',
        '| `safe` | Safe, Unsafe |',
        '',
        '## Key Features',
        '',
        '- View all employee equipment check submissions',
        '- Attach evidence documents to existing checks',
        '- Edit condition and safety status',
        '- Search by operative name',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Civils Trailer Driver (6), Essex Supervisor (8) | List |',
        '| Admin (1), Admin1 (4), Admin2 (7), Civils Trailer Driver (6) | View detail |',
        '| Admin (1) | Edit + delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `equipmentcheck` and `upload_presite` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Site Inspections',
      description: [
        'Site inspection management. Administrators review multi-part PUWER inspections, update status, and manage the post-inspection workflow.',
        '',
        '## Source Discriminator',
        '',
        'A `source` query parameter (required on all endpoints) selects the inspection type:',
        '',
        '| Source | Table | Parent Table |',
        '|--------|-------|--------------|',
        '| `civils` | `insp` | `civils` |',
        '| `wildanet` | `winsp` | `wildanet` |',
        '',
        '## Status Workflow',
        '',
        '```',
        'In Progress → Inspection Awaiting Review → Pass / Completed / Failed / Follow up Required',
        '```',
        '',
        'Admin sets the final status after reviewing the completed 8-part inspection.',
        '',
        '## Key Features',
        '',
        '- Filter by status: `live` (not Completed), `completed`, or all',
        '- Search by `in6` (Site Ganger) prefix match',
        '- Update any field including status transitions',
        '- Full detail view with all 8 image columns expanded to URLs',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Essex Supervisor (8), Customer (9) | List |',
        '| Admin (1), Admin1 (4), Essex Supervisor (8) | View + edit |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `insp` / `winsp` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Vehicle Inspections',
      description: [
        'Vehicle Inspection Checklist (VIC) management. Administrators review 4-part vehicle inspections, manage linked repair records (VIR), and update inspection details.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `vic` | Vehicle inspection records (109 columns) |',
        '| `vir` | Linked inspection repair records |',
        '',
        '## Status Workflow',
        '',
        'VIC: `In Progress` → `Completed` (2 states only)',
        '',
        'VIR: Always `Completed` (no workflow)',
        '',
        '## Key Features',
        '',
        '- View all VIC submissions with full detail',
        '- Edit any inspection fields',
        '- View and manage linked VIR (repair) records per inspection',
        '- Search by `vic2` (vehicle registration) prefix match',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Essex Supervisor (8) | List |',
        '| Admin (1), Admin1 (4), Essex Supervisor (8), Admin2 (7) | View detail + view repairs |',
        '| Admin (1), Admin1 (4) | Edit |',
        '| Admin (1) | Delete VIC + delete VIR |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `vic` and `vir` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Wildanet Jobs',
      description: [
        'Wildanet civils job management. Full lifecycle management of Wildanet project jobs including document uploads and status tracking.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `wildanet` | Job records |',
        '| `wupload_data` | Job documents and attachments |',
        '',
        '## Job Statuses',
        '',
        'Active: any status not in the inactive list.',
        '',
        'Inactive: `Completed`, `Cancelled`, `Closed`, `Invoiced`, `Awaiting Invoicing`.',
        '',
        '## Key Features',
        '',
        '- Full CRUD for job records',
        '- Multi-image job pack upload on create (max 4)',
        '- Typed document management with upload (supports images, PDFs, Office docs, ZIP, XLSX)',
        '- Job fields: status, assigned to, client, authority, community, solo number, location, permit status',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Admin2 (7), Essex Supervisor (8) | List |',
        '| Admin (1), Admin1 (4), Admin2 (7), Civils Trailer Driver (6), Essex Supervisor (8) | View detail |',
        '| Admin (1), Admin1 (4), Admin2 (7) | Edit + upload docs |',
        '| Admin (1) | Create + delete |',
        '| + Customer (9) | View documents only |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `wildanet` and `wupload_data` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Civils',
      description: [
        'Civils job register management. Full lifecycle CRUD for civils job records with document upload.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `civils` | Job register records |',
        '| `upload_data` | Job documents and attachments |',
        '',
        '## Key Features',
        '',
        '- Full CRUD for job records',
        '- Document upload with multiple MIME types supported (images, PDFs, Office docs, ZIP, XLSX)',
        '- Admin list shows all records with filter by status and permit',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Admin2 (7), Essex Supervisor (8) | List |',
        '| Admin (1), Admin1 (4), Admin2 (7), Civils Trailer Driver (6), Essex Supervisor (8) | View detail |',
        '| Admin (1), Admin1 (4), Admin2 (7) | Create + edit + delete + upload docs + delete docs |',
        '| + Customer (9) | View documents only |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `civils` and `upload_data` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - TFL',
      description: [
        'TFL job register and materials management. Full lifecycle CRUD for TFL job records, documents, and material inventory.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `tfl` | TFL job register records |',
        '| `upload_tfl` | Job documents and attachments |',
        '| `tflmaterial` | Material inventory |',
        '',
        '## Key Features',
        '',
        '- Full CRUD for TFL jobs with document upload',
        '- Material inventory management (separate CRUD)',
        '- Admin list shows all records with filter by status and permit',
        '- Material create is open to most roles (except Customer)',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4) | Full job + document management |',
        '| Admin (1) | Delete documents + delete materials |',
        '| Admin (1), Admin1 (4), Civils TFL Driver (5) | View jobs + documents + materials, edit materials |',
        '| All except Customer (9) | Create materials |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `tfl`, `upload_tfl`, and `tflmaterial` tables as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Work Records',
      description: [
        'Work record management. Administrators review field work records submitted by employees and update status.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `workrecord` | Work records |',
        '',
        '## Key Features',
        '',
        '- View all work records across all employees',
        '- Update status and details',
        '- Pending records sorted oldest-first (ASC); others sorted newest-first (DESC)',
        '- Search by employee name',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4) | View + edit |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `workrecord` table as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Clegg Testing',
      description: [
        'Clegg soil compaction test management. Administrators review test results submitted by employees.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `cleggtesting` | Test records |',
        '',
        '## Key Features',
        '',
        '- View all Clegg test submissions',
        '- Edit test details and results',
        '- Search by job number or location',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1) | View + edit + delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `cleggtesting` table as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - Wildanet Risk Assessments',
      description: [
        'Wildanet risk assessment management. Administrators review multi-part risk assessments, update fields, and manage the post-assessment workflow.',
        '',
        '## Database',
        '',
        '| Table | Purpose |',
        '|-------|---------|',
        '| `wra` | Risk assessment records (74 columns) |',
        '',
        '## Status Workflow',
        '',
        '```',
        'In Progress → RA Completed',
        '```',
        '',
        'Admin can edit any field after the 5-part wizard is completed by the employee.',
        '',
        '## Key Features',
        '',
        '- View all risk assessments across all employees',
        '- Edit any assessment fields',
        '- Search by site reference or employee name',
        '- Filter by status',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1), Admin1 (4), Admin2 (7), Civils Trailer Driver (6), Essex Supervisor (8) | List |',
        '| Admin (1), Admin1 (4), Essex Supervisor (8) | View + edit |',
        '| Admin (1) | Delete |',
        '',
        '## PHP Compatibility',
        '',
        'Manages the same `wra` table as PHP admin.',
      ].join('\n'),
    },
    {
      name: 'Admin - PIA & Fibre Risk',
      description: [
        'PIA & Fibre Risk permit deletion. Admin-only endpoint for removing submitted WAH, UG, and MEWP permits.',
        '',
        '## Permit Types',
        '',
        '| Type | Table |',
        '|------|-------|',
        '| WAH (Working at Height) | `wah` |',
        '| UG (Underground Works) | `ug` |',
        '| MEWP (Mobile Elevated Work Platform) | `mewp` |',
        '',
        '## Key Features',
        '',
        '- Delete individual permits by type and ID',
        '- Separate DELETE endpoint per permit type',
        '',
        '## RBAC',
        '',
        '| Role | Access |',
        '|------|--------|',
        '| Admin (1) | Delete only |',
        '',
        '## PHP Compatibility',
        '',
        'Deletes from the same `wah`, `ug`, and `mewp` tables as PHP.',
      ].join('\n'),
    },
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      },
    },
    schemas: {
      ApiSuccess: {
        type: 'object',
        description: 'Standard success envelope returned by all endpoints.',
        properties: {
          success: { type: 'boolean', example: true },
          data: { description: 'Endpoint-specific payload (object or array).' },
          meta: {
            $ref: '#/components/schemas/PaginationMeta',
          },
        },
      },
      ApiError: {
        type: 'object',
        description:
          'Standard error envelope. Every non-2xx response uses this shape. `code` is a machine-readable constant; `message` is human-readable.',
        properties: {
          success: { type: 'boolean', example: false },
          error: {
            type: 'object',
            properties: {
              code: {
                type: 'string',
                example: 'VALIDATION_ERROR',
                description:
                  'Machine-readable error code. Common values: VALIDATION_ERROR, UNAUTHORIZED, AUTH_TOKEN_EXPIRED, AUTH_INVALID_CREDENTIALS, AUTH_USER_DISABLED, AUTH_REFRESH_INVALID, FORBIDDEN, NOT_FOUND, RATE_LIMITED, INTERNAL_ERROR.',
              },
              message: {
                type: 'string',
                example: 'Invalid credentials',
                description: 'Human-readable error description.',
              },
              details: {
                nullable: true,
                description:
                  'Additional error context. For VALIDATION_ERROR this is an array of field-level issues from Zod.',
              },
              requestId: {
                type: 'string',
                example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                description: 'Unique request identifier for support/debugging.',
              },
            },
          },
        },
      },
      PaginationMeta: {
        type: 'object',
        nullable: true,
        description: 'Pagination metadata returned with paginated list endpoints. Null on non-list responses.',
        properties: {
          page: { type: 'integer', example: 1, description: 'Current page number (1-based).' },
          limit: { type: 'integer', example: 20, description: 'Items per page.' },
          total: { type: 'integer', example: 142, description: 'Total matching rows across all pages.' },
        },
      },
      ErrorEnvelope: {
        deprecated: true,
        description: 'Deprecated — use ApiError instead. Will be removed when all modules are migrated.',
        allOf: [{ $ref: '#/components/schemas/ApiError' }],
      },
    },
    responses: {
      Unauthorized401: {
        description: 'Missing or invalid bearer token.',
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/ApiError' },
            examples: {
              tokenExpired: {
                summary: 'Access token expired',
                value: {
                  success: false,
                  error: {
                    code: 'AUTH_TOKEN_EXPIRED',
                    message: 'Access token has expired',
                    details: null,
                    requestId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                  },
                },
              },
              tokenInvalid: {
                summary: 'Malformed or tampered JWT',
                value: {
                  success: false,
                  error: {
                    code: 'AUTH_TOKEN_INVALID',
                    message: 'Invalid access token',
                    details: null,
                    requestId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                  },
                },
              },
              noHeader: {
                summary: 'No Authorization header',
                value: {
                  success: false,
                  error: {
                    code: 'UNAUTHORIZED',
                    message: 'Authentication required',
                    details: null,
                    requestId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                  },
                },
              },
            },
          },
        },
      },
      Forbidden403: {
        description: 'Authenticated but insufficient permissions.',
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/ApiError' },
            example: {
              success: false,
              error: {
                code: 'FORBIDDEN',
                message: 'Insufficient permissions',
                details: null,
                requestId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
              },
            },
          },
        },
      },
      NotFound404: {
        description: 'Resource not found.',
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/ApiError' },
            example: {
              success: false,
              error: {
                code: 'NOT_FOUND',
                message: 'Resource not found',
                details: null,
                requestId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
              },
            },
          },
        },
      },
      ValidationError422: {
        description: 'Request body or query failed Zod validation.',
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/ApiError' },
            example: {
              success: false,
              error: {
                code: 'VALIDATION_ERROR',
                message: 'Validation failed',
                details: [
                  {
                    code: 'too_small',
                    minimum: 1,
                    type: 'string',
                    inclusive: true,
                    exact: false,
                    message: 'String must contain at least 1 character(s)',
                    path: ['field'],
                  },
                ],
                requestId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
              },
            },
          },
        },
      },
      RateLimited429: {
        description: 'Too many requests — back off and retry.',
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/ApiError' },
            example: {
              success: false,
              error: {
                code: 'RATE_LIMITED',
                message: 'Too many requests, please try again later',
                details: null,
                requestId: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
              },
            },
          },
        },
      },
    },
  },
  security: [{ bearerAuth: [] }],
  'x-tagGroups': [
    {
      name: 'Authentication',
      tags: ['Authentication'],
    },
    {
      name: 'Common APIs',
      tags: ['Devices', 'Bulletins', 'Contacts', 'Documents', 'Onboarding'],
    },
    {
      name: 'Employee APIs',
      tags: [
        'Vehicle Checks',
        'Timesheets',
        'Incidents',
        'Equipment Checks',
        'Site Inspections',
        'Vehicle Inspections',
        'Work Records',
        'Clegg Testing',
        'Wildanet Risk Assessments',
        'PIA & Fibre Risk',
        'Wildanet Jobs',
        'Civils',
        'TFL',
      ],
    },
    {
      name: 'Admin APIs',
      tags: [
        'Admin - Bulletins',
        'Admin - Documents',
        'Admin - Vehicle Checks',
        'Admin - Timesheets',
        'Admin - Incidents',
        'Admin - HR',
        'Admin - Users',
        'Admin - Equipment Register',
        'Admin - Vehicle Register',
        'Admin - Plant Register',
        'Admin - Equipment Checks',
        'Admin - Site Inspections',
        'Admin - Vehicle Inspections',
        'Admin - Wildanet Jobs',
        'Admin - Civils',
        'Admin - TFL',
        'Admin - Work Records',
        'Admin - Clegg Testing',
        'Admin - Wildanet Risk Assessments',
        'Admin - PIA & Fibre Risk',
      ],
    },
  ],
};

const options = {
  definition,
  // Use relative forward-slash globs — glob-parent + fast-glob on Windows
  // treats absolute paths built with `path.join` (backslashes) as literal
  // filenames and finds nothing.
  apis: [
    './src/modules/**/*.routes.js',
    './src/modules/**/*.dto.js',
  ],
};

const spec = swaggerJsdoc(options);

module.exports = spec;
